{
  "hash": "ddb2cbe029728274da3c3716cc82f1e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estadística I\"\nsubtitle: \"Guía de Ejercicios: La Distribución Binomial (Clase 13) y la Distribución Normal (Clase1 14)\"\ndate: \"2026/02/23\"\nformat: revealjs\nlang: es\nauthor: M.Sc. José Miguel Avendaño I.\nincremental: false\nauto-stretch: false\nfig-align: center\nexecute:\n  echo: true\n  eval: true\n  code-fold: true\n  code-summary: \"mostrár código\"\n  fig-align: center\n---\n\n\n\n## Dist. Binomial\n\nLa distribución binomial es un modelo de probabilidad discreta que describe el número de éxitos en una secuencia de $n$ ensayos independientes de Bernoulli, con una probabilidad fija $p$ de ocurrencia del éxito entre los ensayos.\n\n------------------------------------------------------------------------\n\n## Cálculos Manuales (Sin R) {.small}\n\nEl objetivo de esta sección es comprender la estructura de la función de probabilidad de la distribución binomial:\n\n$$P(X = k) = \\binom{n}{k} p^k (1-p)^{n-k}$$\n\nDonde:\n\n\\- $n$ es el número de ensayos.\n\n\\- $k$ es el número de éxitos deseados.\n\n\\- $p$ es la probabilidad de éxito en un ensayo dado.\n\n\\- $\\binom{n}{k} = \\frac{n!}{k!(n-k)!}$ es el coeficiente binomial.\n\n## Ejercicio 1: Probabilidad Exacta (Riesgo Crediticio)\n\nUn analista de crédito en un banco determina que la probabilidad de que un cliente de cierto segmento incurra en impago (default) en su primer año es del $10\\%$ ($p = 0.10$). Si se selecciona una muestra aleatoria de $4$ clientes de este segmento: **¿Cuál es la probabilidad de que exactamente 1 cliente incurra en impago?**\n\n## **Solución Manual** Ejercicio 1**:**\n\n\\- $n = 4$\n\n\\- $k = 1$\n\n\\- $p = 0.10$\n\n$$P(X = 1) = \\binom{4}{1} (0.10)^1 (0.90)^3 = 4 \\times 0.10 \\times 0.729 = 0.2916$$ La probabilidad es del $29.16\\%$.\n\n## Ejercicio 2: Probabilidad Acumulada (Lanzamiento de un Producto) {.small}\n\nUna pequeña empresa de software sabe por experiencia que el $20\\%$ de los usuarios que descargan la versión de prueba de su programa terminan comprando la licencia ($p = 0.20$). Si hoy $5$ usuarios descargaron la prueba: **¿Cuál es la probabilidad de que máximo 2 usuarios compren la licencia?**\n\n## **Solución Manual** Ejercicio 2**:**\n\nPara hallar $P(X \\le 2)$, debemos calcular y sumar las probabilidades individuales de $X = 0$, $X = 1$ y $X = 2$.\n\n-   $P(X = 0) = \\binom{5}{0} (0.20)^0 (0.80)^5 = 1 \\times 1 \\times 0.32768 = 0.32768$\n-   $P(X = 1) = \\binom{5}{1} (0.20)^1 (0.80)^4 = 5 \\times 0.20 \\times 0.4096 = 0.4096$\n-   $P(X = 2) = \\binom{5}{2} (0.20)^2 (0.80)^3 = 10 \\times 0.04 \\times 0.512 = 0.2048$\n\n$$P(X \\le 2) = 0.32768 + 0.4096 + 0.2048 = 0.94208$$\n\n::: notes\n*Nota cómo el cálculo manual se vuelve tedioso rápidamente. ¿Qué pasaría si tuviéramos 100 usuarios y quisiéramos saber la probabilidad de que máximo 40 compren la licencia? ¡Tendríamos que calcular y sumar 41 fórmulas distintas! Aquí es donde R se vuelve una herramienta indispensable.*\n:::\n\n------------------------------------------------------------------------\n\n## Cálculos con R\n\nEn R, contamos con cuatro funciones principales para trabajar con cualquier distribución. Para la binomial, estas son:\n\n\\- `dbinom()`: Densidad o probabilidad exacta $P(X = k)$.\n\n\\- `pbinom()`: Probabilidad acumulada $P(X \\le k)$.\n\n\\- `qbinom()`: Cuantiles (el valor de $k$ dada una probabilidad).\n\n\\- `rbinom()`: Generación de números aleatorios (simulación).\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Ejercicio 3: Probabilidad Exacta con `dbinom` (Auditoría de Facturas) {.small}\n\nUna empresa de contabilidad sabe que el $5\\%$ de las facturas que procesa tienen algún error menor. En una auditoría de rutina, se revisan $50$ facturas. **¿Cuál es la probabilidad de que se encuentren exactamente 4 facturas con errores?**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 50\np <- 0.05\nk <- 4\n\ndbinom(x = k, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1359752\n```\n\n\n:::\n\n```{.r .cell-code}\ndbinom(x = 4, size = 50, prob = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1359752\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 4: Probabilidad Acumulada con `pbinom` (Control de Calidad) {.small}\n\nUna fábrica produce microchips, y la tasa histórica de defectos es del $2\\%$. Un lote se aprueba si en una muestra de $100$ chips hay 3 o menos defectuos. **¿Cuál es la probabilidad de aprobar un lote?** $P(X \\le 3)$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 100\np <- 0.02\nk <- 3\n\npbinom(q = k, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8589616\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 5: Probabilidad de la Cola Superior (Ventas de Seguros) {.xsmall}\n\nUn agente de seguros tiene una tasa de éxito del $15\\%$ al contactar prospectos en frío. Si en una semana contacta a $80$ personas: **¿Cuál es la probabilidad de que logre vender más de 15 pólizas?** $P(X > 15)$\n\n*Nota: `pbinom` calcula* $P(X \\le k)$. Para $P(X > k)$, calculamos $1 - P(X \\le 15)$ o usamos el argumento `lower.tail = FALSE`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 80\np <- 0.15\nk <- 15\n\n# Método 1\n1 - pbinom(q = k, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1375337\n```\n\n\n:::\n\n```{.r .cell-code}\n# Método 2 (Recomendado)\npbinom(q = k, size = n, prob = p, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1375337\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 6: Probabilidad en un Rango (Análisis de Encuestas)\n\nEn una encuesta nacional de consumo, se sabe que el $40\\%$ de la población prefiere la marca \"A\". Si tomamos una muestra de $200$ individuos: **¿Cuál es la probabilidad de que entre 70 y 90 personas (ambos inclusive) prefieran la marca \"A\"?** $P(70 \\le X \\le 90)$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200\np <- 0.40\n\n# Calculamos P(X <= 90) y le restamos P(X <= 69) para incluir el 70.\npbinom(90, n, p) - pbinom(69, n, p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8706073\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 7: Uso de Cuantiles con `qbinom` (Planificación de Inventario) {.small}\n\nUna tienda de retail vende laptops durante promociones. La probabilidad de que un visitante compre una laptop es del $8\\%$. Si se esperan $500$ visitantes en un día, el gerente quiere asegurar suficiente inventario. **¿Cuántas laptops debe tener en stock para satisfacer la demanda con una certeza del** $95\\%$?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 500\np <- 0.08\ncerteza <- 0.95\n\nstock_necesario <- qbinom(p = certeza, size = n, prob = p)\nstock_necesario\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 8: Simulación con `rbinom` (Proyección de Crecimiento) {.small}\n\nSupongamos que una startup presenta su proyecto a varios fondos de inversión. La probabilidad de que un fondo decida invertir es del $12\\%$. La startup presenta a $20$ fondos cada mes. **Simula el número de inversiones conseguidas por mes durante un periodo de 2 años (24 meses).**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeses <- 24\nn_fondos <- 20\np_exito <- 0.12\n\nset.seed(123) # Para reproducibilidad\nsimulacion_inversiones <- rbinom(n = meses, size = n_fondos, prob = p_exito)\nsimulacion_inversiones\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 1 4 2 4 5 0 2 4 2 2 5 2 3 3 1 4 1 0 2 5 4 3 3 7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Media empírica de nuestra simulación\nmean(simulacion_inversiones)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.875\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 9: Visualización de la Función de Masa de Probabilidad (PMF) {.small}\n\nVisualizar la distribución nos ayuda a entender dónde se concentra la probabilidad. **Genera un gráfico de barras de la distribución binomial para el escenario de la startup (n = 20, p = 0.12).**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 20\np <- 0.12\nx <- 0:n\nprobabilidades <- dbinom(x, size = n, prob = p)\n\ndf_binomial <- data.frame(Exitos = x, Probabilidad = probabilidades)\ndf_binomial\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Exitos Probabilidad\n1       0 7.756279e-02\n2       1 2.115349e-01\n3       2 2.740338e-01\n4       3 2.242095e-01\n5       4 1.299396e-01\n6       5 5.670092e-02\n7       6 1.932986e-02\n8       7 5.271779e-03\n9       8 1.168178e-03\n10      9 2.123961e-04\n11     10 3.185941e-05\n12     11 3.949514e-06\n13     12 4.039275e-07\n14     13 3.389602e-08\n15     14 2.311092e-09\n16     15 1.260596e-10\n17     16 5.371857e-12\n18     17 1.723590e-13\n19     18 3.917251e-15\n20     19 5.622848e-17\n21     20 3.833760e-19\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 9: cont.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filtramos solo hasta 10 éxitos para ver mejor el gráfico,\n# ya que la probabilidad de 11+ es casi nula.\ngrafico_binomial <- df_binomial %>%\n  filter(Exitos <= 10) %>%\n  ggplot(aes(x = factor(Exitos), y = Probabilidad)) +\n  geom_col(fill = \"steelblue\", color = \"black\", alpha = 0.8) +\n  geom_text(aes(label = round(Probabilidad, 3)), vjust = -0.5, size = 3.5) +\n  labs(title = \"Distribución Binomial: Inversiones Conseguidas\",\n       subtitle = \"n = 20 ensayos, p = 0.12\",\n       x = \"Número de Inversiones (Éxitos)\",\n       y = \"Probabilidad\") +\n  theme_minimal()\n```\n:::\n\n\n\n## Ejercicio 9 Gráfico\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrafico_binomial\n```\n\n::: {.cell-output-display}\n![](clase_13_14_practica_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n## Ejercicio 10: Valor Esperado y Varianza Teórica vs. Empírica\n\nPara una distribución binomial, sabemos que: - Esperanza matemática: $E(X) = n \\cdot p$ - Varianza: $V(X) = n \\cdot p \\cdot (1-p)$\n\n**Compara estos valores teóricos con los resultados de una simulación a gran escala (10,000 observaciones) para un portafolio de** $150$ acciones donde la probabilidad de que una acción supere el rendimiento del mercado es del $45\\%$.\n\n## Ejercicio 10- cont.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_acciones <- 150\np_superar <- 0.45\nn_simulaciones <- 10000\n\n# Cálculos Teóricos\nesperanza_teorica <- n_acciones * p_superar\nvarianza_teorica <- n_acciones * p_superar * (1 - p_superar)\n\n# Simulación Empírica\nset.seed(456)\nsim_gran_escala <- rbinom(n_simulaciones, size = n_acciones, prob = p_superar)\n\nmedia_empirica <- mean(sim_gran_escala)\nvarianza_empirica <- var(sim_gran_escala)\n\n# Resultados\ncat(\"Esperanza Teórica: \", esperanza_teorica, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEsperanza Teórica:  67.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Media Empírica: \", media_empirica, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedia Empírica:  67.5883 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Varianza Teórica: \", varianza_teorica, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVarianza Teórica:  37.125 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Varianza Empírica: \", varianza_empirica, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVarianza Empírica:  37.79898 \n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 10 cont.\n\nLa Ley de los Grandes Números asegura que las simulaciones en R converjan de manera muy precisa a los parámetros poblacionales teóricos, lo cual es fundamental para el modelaje de riesgos económicos.\n\n## Dist. Normal\n\nLa distribución normal es el modelo continuo más importante en estadística. Una variable aleatoria $X$ sigue una distribución normal si su función de densidad de probabilidad forma una curva simétrica en forma de campana, completamente determinada por dos parámetros: su media ($\\mu$) y su desviación estándar ($\\sigma$). Lo denotamos como $X \\sim N(\\mu, \\sigma^2)$.\n\nEn R, utilizamos el sufijo `norm` acompañado de las letras `d`, `p`, `q` y `r` para realizar cálculos de densidad, probabilidad acumulada, cuantiles y simulaciones aleatorias, respectivamente.\n\n------------------------------------------------------------------------\n\n### Ejercicio 11: Probabilidad de un valor inferior con `pnorm` (Gasto del Consumidor) {.small}\n\nUn estudio de mercado indica que el gasto mensual en entretenimiento de los hogares en cierta ciudad se distribuye normalmente con una media de \\$150 mensuales y una desviación estándar de \\$30. **¿Cuál es la probabilidad de que un hogar seleccionado al azar gaste menos de \\$100 al mes en entretenimiento?** $P(X < 100)$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 150\nsigma <- 30\nx <- 100\n\npnorm(q = x, mean = mu, sd = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04779035\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 11: *Interpretación:*\n\n*Hay aproximadamente un 4.78% de probabilidad de que un hogar gaste menos de \\$100 en entretenimiento.*\n\n------------------------------------------------------------------------\n\n## Ejercicio 12: Probabilidad en un intervalo (Salarios en la Industria)\n\nEl salario mensual de los analistas financieros junior en un país sigue una distribución normal con una media de \\$1200 y una desviación estándar de \\$150. **¿Cuál es la probabilidad de que un analista gane entre \\$1000 y \\$1400 mensuales?** $P(1000 < X < 1400)$\n\n## Ejercicio 12: Códigos\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_salario <- 1200\nsigma_salario <- 150\nlimite_inf <- 1000\nlimite_sup <- 1400\n\n# Calculamos P(X < 1400) y le restamos P(X < 1000)\nprob_intervalo <- pnorm(limite_sup, mu_salario, sigma_salario) - \n                  pnorm(limite_inf, mu_salario, sigma_salario)\nprob_intervalo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8175776\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 12 Interpretación*:* \n\n*Aproximadamente el 81.76% de los analistas financieros junior tienen un salario dentro de este rango.*\n\n------------------------------------------------------------------------\n\n## Ejercicio 13: Encontrando percentiles con `qnorm` (Garantía de Tiempos de Entrega)\n\nUna empresa de logística promete entregas rápidas. Sabe que el tiempo de entrega de sus paquetes se distribuye normalmente con una media de 45 minutos y una desviación estándar de 8 minutos. La gerencia quiere establecer un tiempo máximo garantizado para su campaña publicitaria de modo que cumplan con el 95% de las entregas. **¿Cuál debe ser ese tiempo garantizado?** (Buscamos el percentil 95).\n\n## Ejercicio 13 códigos\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_tiempo <- 45\nsigma_tiempo <- 8\nprob_objetivo <- 0.95\n\ntiempo_garantizado <- qnorm(p = prob_objetivo, mean = mu_tiempo, sd = sigma_tiempo)\ntiempo_garantizado\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58.15883\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 13 Interpretación: \n\n*Para cumplir con el 95% de los clientes, la empresa debería garantizar la entrega en 58.16 minutos (podría redondearse a 60 minutos por razones de marketing).*\n\n------------------------------------------------------------------------\n\n## Ejercicio 14: Simulación de escenarios con `rnorm` (Rendimiento de Acciones)\n\nSupongamos que el rendimiento diario de una acción en la bolsa de valores sigue una distribución normal con un rendimiento medio del 0.05% (0.0005) y una volatilidad (desviación estándar) del 2% (0.02). **Simula los rendimientos diarios de esta acción para los próximos 100 días de cotización e identifica cuántos días tuvieron un rendimiento negativo.**\n\n## Ejercicio 14 Códigos\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_rend <- 0.0005\nsigma_rend <- 0.02\ndias <- 100\n\nset.seed(789) # Para que todos los estudiantes obtengan el mismo resultado\nsimulacion_rendimientos <- rnorm(n = dias, mean = mu_rend, sd = sigma_rend)\n\n# Contar cuántos días el rendimiento fue menor a 0\ndias_negativos <- sum(simulacion_rendimientos < 0)\n\npaste(\"De los 100 días simulados,\", dias_negativos, \"tuvieron rendimientos negativos.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"De los 100 días simulados, 53 tuvieron rendimientos negativos.\\n\"\n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Ejercicio 15: Visualización de la Curva Normal con `dnorm` y `ggplot2`\n\nPara entender mejor la distribución del Ejercicio 2 (Salarios), vamos a graficar la curva de densidad normal correspondiente y sombrear el área que representa a los analistas que ganan menos de \\$1000.\n\n## Ejercicio 15 Códigos\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creamos un rango de valores para el eje X (Salarios)\n# Usualmente graficamos +/- 4 desviaciones estándar desde la media\nx_salarios <- seq(1200 - 4*150, 1200 + 4*150, length.out = 1000)\n\n# Calculamos la densidad (eje Y) para cada salario\ny_densidad <- dnorm(x_salarios, mean = 1200, sd = 150)\n\n# Creamos un dataframe para ggplot\ndf_salarios <- data.frame(Salario = x_salarios, Densidad = y_densidad)\n\ndf_salarios\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Salario     Densidad\n1     600.0000 8.922015e-07\n2     601.2012 9.212136e-07\n3     602.4024 9.511082e-07\n4     603.6036 9.819099e-07\n5     604.8048 1.013644e-06\n6     606.0060 1.046337e-06\n7     607.2072 1.080015e-06\n8     608.4084 1.114705e-06\n9     609.6096 1.150436e-06\n10    610.8108 1.187236e-06\n11    612.0120 1.225135e-06\n12    613.2132 1.264162e-06\n13    614.4144 1.304349e-06\n14    615.6156 1.345727e-06\n15    616.8168 1.388329e-06\n16    618.0180 1.432187e-06\n17    619.2192 1.477337e-06\n18    620.4204 1.523811e-06\n19    621.6216 1.571648e-06\n20    622.8228 1.620882e-06\n21    624.0240 1.671551e-06\n22    625.2252 1.723693e-06\n23    626.4264 1.777348e-06\n24    627.6276 1.832556e-06\n25    628.8288 1.889357e-06\n26    630.0300 1.947794e-06\n27    631.2312 2.007910e-06\n28    632.4324 2.069748e-06\n29    633.6336 2.133354e-06\n30    634.8348 2.198774e-06\n31    636.0360 2.266054e-06\n32    637.2372 2.335243e-06\n33    638.4384 2.406391e-06\n34    639.6396 2.479547e-06\n35    640.8408 2.554764e-06\n36    642.0420 2.632093e-06\n37    643.2432 2.711589e-06\n38    644.4444 2.793307e-06\n39    645.6456 2.877303e-06\n40    646.8468 2.963635e-06\n41    648.0480 3.052361e-06\n42    649.2492 3.143542e-06\n43    650.4505 3.237240e-06\n44    651.6517 3.333516e-06\n45    652.8529 3.432435e-06\n46    654.0541 3.534064e-06\n47    655.2553 3.638468e-06\n48    656.4565 3.745715e-06\n49    657.6577 3.855877e-06\n50    658.8589 3.969025e-06\n51    660.0601 4.085230e-06\n52    661.2613 4.204568e-06\n53    662.4625 4.327115e-06\n54    663.6637 4.452948e-06\n55    664.8649 4.582146e-06\n56    666.0661 4.714791e-06\n57    667.2673 4.850964e-06\n58    668.4685 4.990751e-06\n59    669.6697 5.134236e-06\n60    670.8709 5.281507e-06\n61    672.0721 5.432655e-06\n62    673.2733 5.587769e-06\n63    674.4745 5.746945e-06\n64    675.6757 5.910275e-06\n65    676.8769 6.077857e-06\n66    678.0781 6.249791e-06\n67    679.2793 6.426176e-06\n68    680.4805 6.607115e-06\n69    681.6817 6.792714e-06\n70    682.8829 6.983078e-06\n71    684.0841 7.178317e-06\n72    685.2853 7.378541e-06\n73    686.4865 7.583863e-06\n74    687.6877 7.794400e-06\n75    688.8889 8.010267e-06\n76    690.0901 8.231585e-06\n77    691.2913 8.458475e-06\n78    692.4925 8.691062e-06\n79    693.6937 8.929472e-06\n80    694.8949 9.173833e-06\n81    696.0961 9.424278e-06\n82    697.2973 9.680938e-06\n83    698.4985 9.943950e-06\n84    699.6997 1.021345e-05\n85    700.9009 1.048959e-05\n86    702.1021 1.077250e-05\n87    703.3033 1.106233e-05\n88    704.5045 1.135923e-05\n89    705.7057 1.166335e-05\n90    706.9069 1.197484e-05\n91    708.1081 1.229387e-05\n92    709.3093 1.262058e-05\n93    710.5105 1.295515e-05\n94    711.7117 1.329773e-05\n95    712.9129 1.364850e-05\n96    714.1141 1.400762e-05\n97    715.3153 1.437527e-05\n98    716.5165 1.475162e-05\n99    717.7177 1.513685e-05\n100   718.9189 1.553115e-05\n101   720.1201 1.593470e-05\n102   721.3213 1.634768e-05\n103   722.5225 1.677029e-05\n104   723.7237 1.720273e-05\n105   724.9249 1.764518e-05\n106   726.1261 1.809786e-05\n107   727.3273 1.856095e-05\n108   728.5285 1.903468e-05\n109   729.7297 1.951924e-05\n110   730.9309 2.001485e-05\n111   732.1321 2.052174e-05\n112   733.3333 2.104011e-05\n113   734.5345 2.157019e-05\n114   735.7357 2.211221e-05\n115   736.9369 2.266639e-05\n116   738.1381 2.323298e-05\n117   739.3393 2.381220e-05\n118   740.5405 2.440429e-05\n119   741.7417 2.500951e-05\n120   742.9429 2.562809e-05\n121   744.1441 2.626028e-05\n122   745.3453 2.690635e-05\n123   746.5465 2.756654e-05\n124   747.7477 2.824112e-05\n125   748.9489 2.893035e-05\n126   750.1502 2.963450e-05\n127   751.3514 3.035384e-05\n128   752.5526 3.108866e-05\n129   753.7538 3.183921e-05\n130   754.9550 3.260580e-05\n131   756.1562 3.338871e-05\n132   757.3574 3.418821e-05\n133   758.5586 3.500462e-05\n134   759.7598 3.583823e-05\n135   760.9610 3.668933e-05\n136   762.1622 3.755824e-05\n137   763.3634 3.844527e-05\n138   764.5646 3.935071e-05\n139   765.7658 4.027490e-05\n140   766.9670 4.121815e-05\n141   768.1682 4.218079e-05\n142   769.3694 4.316314e-05\n143   770.5706 4.416554e-05\n144   771.7718 4.518832e-05\n145   772.9730 4.623182e-05\n146   774.1742 4.729638e-05\n147   775.3754 4.838235e-05\n148   776.5766 4.949009e-05\n149   777.7778 5.061994e-05\n150   778.9790 5.177226e-05\n151   780.1802 5.294742e-05\n152   781.3814 5.414578e-05\n153   782.5826 5.536772e-05\n154   783.7838 5.661360e-05\n155   784.9850 5.788380e-05\n156   786.1862 5.917871e-05\n157   787.3874 6.049870e-05\n158   788.5886 6.184417e-05\n159   789.7898 6.321551e-05\n160   790.9910 6.461312e-05\n161   792.1922 6.603738e-05\n162   793.3934 6.748872e-05\n163   794.5946 6.896753e-05\n164   795.7958 7.047422e-05\n165   796.9970 7.200921e-05\n166   798.1982 7.357292e-05\n167   799.3994 7.516576e-05\n168   800.6006 7.678816e-05\n169   801.8018 7.844055e-05\n170   803.0030 8.012336e-05\n171   804.2042 8.183703e-05\n172   805.4054 8.358198e-05\n173   806.6066 8.535867e-05\n174   807.8078 8.716753e-05\n175   809.0090 8.900902e-05\n176   810.2102 9.088358e-05\n177   811.4114 9.279167e-05\n178   812.6126 9.473375e-05\n179   813.8138 9.671027e-05\n180   815.0150 9.872170e-05\n181   816.2162 1.007685e-04\n182   817.4174 1.028511e-04\n183   818.6186 1.049701e-04\n184   819.8198 1.071258e-04\n185   821.0210 1.093188e-04\n186   822.2222 1.115496e-04\n187   823.4234 1.138185e-04\n188   824.6246 1.161262e-04\n189   825.8258 1.184730e-04\n190   827.0270 1.208596e-04\n191   828.2282 1.232863e-04\n192   829.4294 1.257536e-04\n193   830.6306 1.282621e-04\n194   831.8318 1.308123e-04\n195   833.0330 1.334046e-04\n196   834.2342 1.360396e-04\n197   835.4354 1.387177e-04\n198   836.6366 1.414394e-04\n199   837.8378 1.442053e-04\n200   839.0390 1.470159e-04\n201   840.2402 1.498717e-04\n202   841.4414 1.527731e-04\n203   842.6426 1.557207e-04\n204   843.8438 1.587150e-04\n205   845.0450 1.617565e-04\n206   846.2462 1.648457e-04\n207   847.4474 1.679831e-04\n208   848.6486 1.711693e-04\n209   849.8498 1.744047e-04\n210   851.0511 1.776899e-04\n211   852.2523 1.810253e-04\n212   853.4535 1.844115e-04\n213   854.6547 1.878491e-04\n214   855.8559 1.913384e-04\n215   857.0571 1.948800e-04\n216   858.2583 1.984745e-04\n217   859.4595 2.021223e-04\n218   860.6607 2.058240e-04\n219   861.8619 2.095800e-04\n220   863.0631 2.133909e-04\n221   864.2643 2.172571e-04\n222   865.4655 2.211792e-04\n223   866.6667 2.251577e-04\n224   867.8679 2.291930e-04\n225   869.0691 2.332857e-04\n226   870.2703 2.374362e-04\n227   871.4715 2.416451e-04\n228   872.6727 2.459128e-04\n229   873.8739 2.502399e-04\n230   875.0751 2.546268e-04\n231   876.2763 2.590739e-04\n232   877.4775 2.635818e-04\n233   878.6787 2.681510e-04\n234   879.8799 2.727819e-04\n235   881.0811 2.774749e-04\n236   882.2823 2.822306e-04\n237   883.4835 2.870494e-04\n238   884.6847 2.919318e-04\n239   885.8859 2.968781e-04\n240   887.0871 3.018889e-04\n241   888.2883 3.069646e-04\n242   889.4895 3.121056e-04\n243   890.6907 3.173124e-04\n244   891.8919 3.225853e-04\n245   893.0931 3.279249e-04\n246   894.2943 3.333314e-04\n247   895.4955 3.388054e-04\n248   896.6967 3.443471e-04\n249   897.8979 3.499571e-04\n250   899.0991 3.556356e-04\n251   900.3003 3.613831e-04\n252   901.5015 3.672000e-04\n253   902.7027 3.730866e-04\n254   903.9039 3.790432e-04\n255   905.1051 3.850702e-04\n256   906.3063 3.911680e-04\n257   907.5075 3.973368e-04\n258   908.7087 4.035771e-04\n259   909.9099 4.098890e-04\n260   911.1111 4.162730e-04\n261   912.3123 4.227294e-04\n262   913.5135 4.292583e-04\n263   914.7147 4.358601e-04\n264   915.9159 4.425351e-04\n265   917.1171 4.492834e-04\n266   918.3183 4.561055e-04\n267   919.5195 4.630014e-04\n268   920.7207 4.699714e-04\n269   921.9219 4.770158e-04\n270   923.1231 4.841348e-04\n271   924.3243 4.913284e-04\n272   925.5255 4.985970e-04\n273   926.7267 5.059406e-04\n274   927.9279 5.133595e-04\n275   929.1291 5.208538e-04\n276   930.3303 5.284236e-04\n277   931.5315 5.360691e-04\n278   932.7327 5.437902e-04\n279   933.9339 5.515872e-04\n280   935.1351 5.594602e-04\n281   936.3363 5.674091e-04\n282   937.5375 5.754341e-04\n283   938.7387 5.835351e-04\n284   939.9399 5.917122e-04\n285   941.1411 5.999655e-04\n286   942.3423 6.082948e-04\n287   943.5435 6.167002e-04\n288   944.7447 6.251817e-04\n289   945.9459 6.337392e-04\n290   947.1471 6.423727e-04\n291   948.3483 6.510820e-04\n292   949.5495 6.598670e-04\n293   950.7508 6.687277e-04\n294   951.9520 6.776640e-04\n295   953.1532 6.866756e-04\n296   954.3544 6.957624e-04\n297   955.5556 7.049243e-04\n298   956.7568 7.141610e-04\n299   957.9580 7.234723e-04\n300   959.1592 7.328581e-04\n301   960.3604 7.423180e-04\n302   961.5616 7.518518e-04\n303   962.7628 7.614592e-04\n304   963.9640 7.711399e-04\n305   965.1652 7.808936e-04\n306   966.3664 7.907200e-04\n307   967.5676 8.006187e-04\n308   968.7688 8.105893e-04\n309   969.9700 8.206315e-04\n310   971.1712 8.307448e-04\n311   972.3724 8.409288e-04\n312   973.5736 8.511831e-04\n313   974.7748 8.615071e-04\n314   975.9760 8.719005e-04\n315   977.1772 8.823627e-04\n316   978.3784 8.928931e-04\n317   979.5796 9.034913e-04\n318   980.7808 9.141566e-04\n319   981.9820 9.248886e-04\n320   983.1832 9.356865e-04\n321   984.3844 9.465498e-04\n322   985.5856 9.574778e-04\n323   986.7868 9.684698e-04\n324   987.9880 9.795252e-04\n325   989.1892 9.906433e-04\n326   990.3904 1.001823e-03\n327   991.5916 1.013065e-03\n328   992.7928 1.024366e-03\n329   993.9940 1.035728e-03\n330   995.1952 1.047148e-03\n331   996.3964 1.058626e-03\n332   997.5976 1.070162e-03\n333   998.7988 1.081753e-03\n334  1000.0000 1.093400e-03\n335  1001.2012 1.105102e-03\n336  1002.4024 1.116858e-03\n337  1003.6036 1.128666e-03\n338  1004.8048 1.140525e-03\n339  1006.0060 1.152436e-03\n340  1007.2072 1.164396e-03\n341  1008.4084 1.176405e-03\n342  1009.6096 1.188461e-03\n343  1010.8108 1.200564e-03\n344  1012.0120 1.212713e-03\n345  1013.2132 1.224905e-03\n346  1014.4144 1.237141e-03\n347  1015.6156 1.249420e-03\n348  1016.8168 1.261739e-03\n349  1018.0180 1.274098e-03\n350  1019.2192 1.286495e-03\n351  1020.4204 1.298930e-03\n352  1021.6216 1.311401e-03\n353  1022.8228 1.323907e-03\n354  1024.0240 1.336446e-03\n355  1025.2252 1.349017e-03\n356  1026.4264 1.361620e-03\n357  1027.6276 1.374252e-03\n358  1028.8288 1.386912e-03\n359  1030.0300 1.399599e-03\n360  1031.2312 1.412312e-03\n361  1032.4324 1.425049e-03\n362  1033.6336 1.437808e-03\n363  1034.8348 1.450589e-03\n364  1036.0360 1.463389e-03\n365  1037.2372 1.476208e-03\n366  1038.4384 1.489043e-03\n367  1039.6396 1.501894e-03\n368  1040.8408 1.514759e-03\n369  1042.0420 1.527635e-03\n370  1043.2432 1.540523e-03\n371  1044.4444 1.553419e-03\n372  1045.6456 1.566323e-03\n373  1046.8468 1.579233e-03\n374  1048.0480 1.592148e-03\n375  1049.2492 1.605064e-03\n376  1050.4505 1.617982e-03\n377  1051.6517 1.630900e-03\n378  1052.8529 1.643815e-03\n379  1054.0541 1.656726e-03\n380  1055.2553 1.669631e-03\n381  1056.4565 1.682529e-03\n382  1057.6577 1.695418e-03\n383  1058.8589 1.708296e-03\n384  1060.0601 1.721162e-03\n385  1061.2613 1.734013e-03\n386  1062.4625 1.746848e-03\n387  1063.6637 1.759666e-03\n388  1064.8649 1.772463e-03\n389  1066.0661 1.785240e-03\n390  1067.2673 1.797993e-03\n391  1068.4685 1.810721e-03\n392  1069.6697 1.823422e-03\n393  1070.8709 1.836094e-03\n394  1072.0721 1.848737e-03\n395  1073.2733 1.861346e-03\n396  1074.4745 1.873922e-03\n397  1075.6757 1.886461e-03\n398  1076.8769 1.898963e-03\n399  1078.0781 1.911425e-03\n400  1079.2793 1.923846e-03\n401  1080.4805 1.936222e-03\n402  1081.6817 1.948554e-03\n403  1082.8829 1.960838e-03\n404  1084.0841 1.973074e-03\n405  1085.2853 1.985258e-03\n406  1086.4865 1.997389e-03\n407  1087.6877 2.009466e-03\n408  1088.8889 2.021486e-03\n409  1090.0901 2.033448e-03\n410  1091.2913 2.045349e-03\n411  1092.4925 2.057188e-03\n412  1093.6937 2.068963e-03\n413  1094.8949 2.080672e-03\n414  1096.0961 2.092312e-03\n415  1097.2973 2.103883e-03\n416  1098.4985 2.115383e-03\n417  1099.6997 2.126809e-03\n418  1100.9009 2.138159e-03\n419  1102.1021 2.149432e-03\n420  1103.3033 2.160626e-03\n421  1104.5045 2.171739e-03\n422  1105.7057 2.182769e-03\n423  1106.9069 2.193715e-03\n424  1108.1081 2.204574e-03\n425  1109.3093 2.215345e-03\n426  1110.5105 2.226025e-03\n427  1111.7117 2.236614e-03\n428  1112.9129 2.247109e-03\n429  1114.1141 2.257509e-03\n430  1115.3153 2.267811e-03\n431  1116.5165 2.278014e-03\n432  1117.7177 2.288116e-03\n433  1118.9189 2.298115e-03\n434  1120.1201 2.308011e-03\n435  1121.3213 2.317800e-03\n436  1122.5225 2.327482e-03\n437  1123.7237 2.337054e-03\n438  1124.9249 2.346515e-03\n439  1126.1261 2.355863e-03\n440  1127.3273 2.365097e-03\n441  1128.5285 2.374214e-03\n442  1129.7297 2.383214e-03\n443  1130.9309 2.392095e-03\n444  1132.1321 2.400855e-03\n445  1133.3333 2.409492e-03\n446  1134.5345 2.418006e-03\n447  1135.7357 2.426393e-03\n448  1136.9369 2.434654e-03\n449  1138.1381 2.442787e-03\n450  1139.3393 2.450789e-03\n451  1140.5405 2.458660e-03\n452  1141.7417 2.466398e-03\n453  1142.9429 2.474001e-03\n454  1144.1441 2.481469e-03\n455  1145.3453 2.488800e-03\n456  1146.5465 2.495993e-03\n457  1147.7477 2.503045e-03\n458  1148.9489 2.509957e-03\n459  1150.1502 2.516727e-03\n460  1151.3514 2.523352e-03\n461  1152.5526 2.529833e-03\n462  1153.7538 2.536168e-03\n463  1154.9550 2.542356e-03\n464  1156.1562 2.548396e-03\n465  1157.3574 2.554286e-03\n466  1158.5586 2.560025e-03\n467  1159.7598 2.565613e-03\n468  1160.9610 2.571048e-03\n469  1162.1622 2.576330e-03\n470  1163.3634 2.581457e-03\n471  1164.5646 2.586428e-03\n472  1165.7658 2.591242e-03\n473  1166.9670 2.595899e-03\n474  1168.1682 2.600398e-03\n475  1169.3694 2.604737e-03\n476  1170.5706 2.608916e-03\n477  1171.7718 2.612935e-03\n478  1172.9730 2.616792e-03\n479  1174.1742 2.620486e-03\n480  1175.3754 2.624017e-03\n481  1176.5766 2.627385e-03\n482  1177.7778 2.630588e-03\n483  1178.9790 2.633627e-03\n484  1180.1802 2.636499e-03\n485  1181.3814 2.639206e-03\n486  1182.5826 2.641746e-03\n487  1183.7838 2.644119e-03\n488  1184.9850 2.646324e-03\n489  1186.1862 2.648361e-03\n490  1187.3874 2.650230e-03\n491  1188.5886 2.651930e-03\n492  1189.7898 2.653461e-03\n493  1190.9910 2.654823e-03\n494  1192.1922 2.656015e-03\n495  1193.3934 2.657037e-03\n496  1194.5946 2.657889e-03\n497  1195.7958 2.658571e-03\n498  1196.9970 2.659082e-03\n499  1198.1982 2.659423e-03\n500  1199.3994 2.659594e-03\n501  1200.6006 2.659594e-03\n502  1201.8018 2.659423e-03\n503  1203.0030 2.659082e-03\n504  1204.2042 2.658571e-03\n505  1205.4054 2.657889e-03\n506  1206.6066 2.657037e-03\n507  1207.8078 2.656015e-03\n508  1209.0090 2.654823e-03\n509  1210.2102 2.653461e-03\n510  1211.4114 2.651930e-03\n511  1212.6126 2.650230e-03\n512  1213.8138 2.648361e-03\n513  1215.0150 2.646324e-03\n514  1216.2162 2.644119e-03\n515  1217.4174 2.641746e-03\n516  1218.6186 2.639206e-03\n517  1219.8198 2.636499e-03\n518  1221.0210 2.633627e-03\n519  1222.2222 2.630588e-03\n520  1223.4234 2.627385e-03\n521  1224.6246 2.624017e-03\n522  1225.8258 2.620486e-03\n523  1227.0270 2.616792e-03\n524  1228.2282 2.612935e-03\n525  1229.4294 2.608916e-03\n526  1230.6306 2.604737e-03\n527  1231.8318 2.600398e-03\n528  1233.0330 2.595899e-03\n529  1234.2342 2.591242e-03\n530  1235.4354 2.586428e-03\n531  1236.6366 2.581457e-03\n532  1237.8378 2.576330e-03\n533  1239.0390 2.571048e-03\n534  1240.2402 2.565613e-03\n535  1241.4414 2.560025e-03\n536  1242.6426 2.554286e-03\n537  1243.8438 2.548396e-03\n538  1245.0450 2.542356e-03\n539  1246.2462 2.536168e-03\n540  1247.4474 2.529833e-03\n541  1248.6486 2.523352e-03\n542  1249.8498 2.516727e-03\n543  1251.0511 2.509957e-03\n544  1252.2523 2.503045e-03\n545  1253.4535 2.495993e-03\n546  1254.6547 2.488800e-03\n547  1255.8559 2.481469e-03\n548  1257.0571 2.474001e-03\n549  1258.2583 2.466398e-03\n550  1259.4595 2.458660e-03\n551  1260.6607 2.450789e-03\n552  1261.8619 2.442787e-03\n553  1263.0631 2.434654e-03\n554  1264.2643 2.426393e-03\n555  1265.4655 2.418006e-03\n556  1266.6667 2.409492e-03\n557  1267.8679 2.400855e-03\n558  1269.0691 2.392095e-03\n559  1270.2703 2.383214e-03\n560  1271.4715 2.374214e-03\n561  1272.6727 2.365097e-03\n562  1273.8739 2.355863e-03\n563  1275.0751 2.346515e-03\n564  1276.2763 2.337054e-03\n565  1277.4775 2.327482e-03\n566  1278.6787 2.317800e-03\n567  1279.8799 2.308011e-03\n568  1281.0811 2.298115e-03\n569  1282.2823 2.288116e-03\n570  1283.4835 2.278014e-03\n571  1284.6847 2.267811e-03\n572  1285.8859 2.257509e-03\n573  1287.0871 2.247109e-03\n574  1288.2883 2.236614e-03\n575  1289.4895 2.226025e-03\n576  1290.6907 2.215345e-03\n577  1291.8919 2.204574e-03\n578  1293.0931 2.193715e-03\n579  1294.2943 2.182769e-03\n580  1295.4955 2.171739e-03\n581  1296.6967 2.160626e-03\n582  1297.8979 2.149432e-03\n583  1299.0991 2.138159e-03\n584  1300.3003 2.126809e-03\n585  1301.5015 2.115383e-03\n586  1302.7027 2.103883e-03\n587  1303.9039 2.092312e-03\n588  1305.1051 2.080672e-03\n589  1306.3063 2.068963e-03\n590  1307.5075 2.057188e-03\n591  1308.7087 2.045349e-03\n592  1309.9099 2.033448e-03\n593  1311.1111 2.021486e-03\n594  1312.3123 2.009466e-03\n595  1313.5135 1.997389e-03\n596  1314.7147 1.985258e-03\n597  1315.9159 1.973074e-03\n598  1317.1171 1.960838e-03\n599  1318.3183 1.948554e-03\n600  1319.5195 1.936222e-03\n601  1320.7207 1.923846e-03\n602  1321.9219 1.911425e-03\n603  1323.1231 1.898963e-03\n604  1324.3243 1.886461e-03\n605  1325.5255 1.873922e-03\n606  1326.7267 1.861346e-03\n607  1327.9279 1.848737e-03\n608  1329.1291 1.836094e-03\n609  1330.3303 1.823422e-03\n610  1331.5315 1.810721e-03\n611  1332.7327 1.797993e-03\n612  1333.9339 1.785240e-03\n613  1335.1351 1.772463e-03\n614  1336.3363 1.759666e-03\n615  1337.5375 1.746848e-03\n616  1338.7387 1.734013e-03\n617  1339.9399 1.721162e-03\n618  1341.1411 1.708296e-03\n619  1342.3423 1.695418e-03\n620  1343.5435 1.682529e-03\n621  1344.7447 1.669631e-03\n622  1345.9459 1.656726e-03\n623  1347.1471 1.643815e-03\n624  1348.3483 1.630900e-03\n625  1349.5495 1.617982e-03\n626  1350.7508 1.605064e-03\n627  1351.9520 1.592148e-03\n628  1353.1532 1.579233e-03\n629  1354.3544 1.566323e-03\n630  1355.5556 1.553419e-03\n631  1356.7568 1.540523e-03\n632  1357.9580 1.527635e-03\n633  1359.1592 1.514759e-03\n634  1360.3604 1.501894e-03\n635  1361.5616 1.489043e-03\n636  1362.7628 1.476208e-03\n637  1363.9640 1.463389e-03\n638  1365.1652 1.450589e-03\n639  1366.3664 1.437808e-03\n640  1367.5676 1.425049e-03\n641  1368.7688 1.412312e-03\n642  1369.9700 1.399599e-03\n643  1371.1712 1.386912e-03\n644  1372.3724 1.374252e-03\n645  1373.5736 1.361620e-03\n646  1374.7748 1.349017e-03\n647  1375.9760 1.336446e-03\n648  1377.1772 1.323907e-03\n649  1378.3784 1.311401e-03\n650  1379.5796 1.298930e-03\n651  1380.7808 1.286495e-03\n652  1381.9820 1.274098e-03\n653  1383.1832 1.261739e-03\n654  1384.3844 1.249420e-03\n655  1385.5856 1.237141e-03\n656  1386.7868 1.224905e-03\n657  1387.9880 1.212713e-03\n658  1389.1892 1.200564e-03\n659  1390.3904 1.188461e-03\n660  1391.5916 1.176405e-03\n661  1392.7928 1.164396e-03\n662  1393.9940 1.152436e-03\n663  1395.1952 1.140525e-03\n664  1396.3964 1.128666e-03\n665  1397.5976 1.116858e-03\n666  1398.7988 1.105102e-03\n667  1400.0000 1.093400e-03\n668  1401.2012 1.081753e-03\n669  1402.4024 1.070162e-03\n670  1403.6036 1.058626e-03\n671  1404.8048 1.047148e-03\n672  1406.0060 1.035728e-03\n673  1407.2072 1.024366e-03\n674  1408.4084 1.013065e-03\n675  1409.6096 1.001823e-03\n676  1410.8108 9.906433e-04\n677  1412.0120 9.795252e-04\n678  1413.2132 9.684698e-04\n679  1414.4144 9.574778e-04\n680  1415.6156 9.465498e-04\n681  1416.8168 9.356865e-04\n682  1418.0180 9.248886e-04\n683  1419.2192 9.141566e-04\n684  1420.4204 9.034913e-04\n685  1421.6216 8.928931e-04\n686  1422.8228 8.823627e-04\n687  1424.0240 8.719005e-04\n688  1425.2252 8.615071e-04\n689  1426.4264 8.511831e-04\n690  1427.6276 8.409288e-04\n691  1428.8288 8.307448e-04\n692  1430.0300 8.206315e-04\n693  1431.2312 8.105893e-04\n694  1432.4324 8.006187e-04\n695  1433.6336 7.907200e-04\n696  1434.8348 7.808936e-04\n697  1436.0360 7.711399e-04\n698  1437.2372 7.614592e-04\n699  1438.4384 7.518518e-04\n700  1439.6396 7.423180e-04\n701  1440.8408 7.328581e-04\n702  1442.0420 7.234723e-04\n703  1443.2432 7.141610e-04\n704  1444.4444 7.049243e-04\n705  1445.6456 6.957624e-04\n706  1446.8468 6.866756e-04\n707  1448.0480 6.776640e-04\n708  1449.2492 6.687277e-04\n709  1450.4505 6.598670e-04\n710  1451.6517 6.510820e-04\n711  1452.8529 6.423727e-04\n712  1454.0541 6.337392e-04\n713  1455.2553 6.251817e-04\n714  1456.4565 6.167002e-04\n715  1457.6577 6.082948e-04\n716  1458.8589 5.999655e-04\n717  1460.0601 5.917122e-04\n718  1461.2613 5.835351e-04\n719  1462.4625 5.754341e-04\n720  1463.6637 5.674091e-04\n721  1464.8649 5.594602e-04\n722  1466.0661 5.515872e-04\n723  1467.2673 5.437902e-04\n724  1468.4685 5.360691e-04\n725  1469.6697 5.284236e-04\n726  1470.8709 5.208538e-04\n727  1472.0721 5.133595e-04\n728  1473.2733 5.059406e-04\n729  1474.4745 4.985970e-04\n730  1475.6757 4.913284e-04\n731  1476.8769 4.841348e-04\n732  1478.0781 4.770158e-04\n733  1479.2793 4.699714e-04\n734  1480.4805 4.630014e-04\n735  1481.6817 4.561055e-04\n736  1482.8829 4.492834e-04\n737  1484.0841 4.425351e-04\n738  1485.2853 4.358601e-04\n739  1486.4865 4.292583e-04\n740  1487.6877 4.227294e-04\n741  1488.8889 4.162730e-04\n742  1490.0901 4.098890e-04\n743  1491.2913 4.035771e-04\n744  1492.4925 3.973368e-04\n745  1493.6937 3.911680e-04\n746  1494.8949 3.850702e-04\n747  1496.0961 3.790432e-04\n748  1497.2973 3.730866e-04\n749  1498.4985 3.672000e-04\n750  1499.6997 3.613831e-04\n751  1500.9009 3.556356e-04\n752  1502.1021 3.499571e-04\n753  1503.3033 3.443471e-04\n754  1504.5045 3.388054e-04\n755  1505.7057 3.333314e-04\n756  1506.9069 3.279249e-04\n757  1508.1081 3.225853e-04\n758  1509.3093 3.173124e-04\n759  1510.5105 3.121056e-04\n760  1511.7117 3.069646e-04\n761  1512.9129 3.018889e-04\n762  1514.1141 2.968781e-04\n763  1515.3153 2.919318e-04\n764  1516.5165 2.870494e-04\n765  1517.7177 2.822306e-04\n766  1518.9189 2.774749e-04\n767  1520.1201 2.727819e-04\n768  1521.3213 2.681510e-04\n769  1522.5225 2.635818e-04\n770  1523.7237 2.590739e-04\n771  1524.9249 2.546268e-04\n772  1526.1261 2.502399e-04\n773  1527.3273 2.459128e-04\n774  1528.5285 2.416451e-04\n775  1529.7297 2.374362e-04\n776  1530.9309 2.332857e-04\n777  1532.1321 2.291930e-04\n778  1533.3333 2.251577e-04\n779  1534.5345 2.211792e-04\n780  1535.7357 2.172571e-04\n781  1536.9369 2.133909e-04\n782  1538.1381 2.095800e-04\n783  1539.3393 2.058240e-04\n784  1540.5405 2.021223e-04\n785  1541.7417 1.984745e-04\n786  1542.9429 1.948800e-04\n787  1544.1441 1.913384e-04\n788  1545.3453 1.878491e-04\n789  1546.5465 1.844115e-04\n790  1547.7477 1.810253e-04\n791  1548.9489 1.776899e-04\n792  1550.1502 1.744047e-04\n793  1551.3514 1.711693e-04\n794  1552.5526 1.679831e-04\n795  1553.7538 1.648457e-04\n796  1554.9550 1.617565e-04\n797  1556.1562 1.587150e-04\n798  1557.3574 1.557207e-04\n799  1558.5586 1.527731e-04\n800  1559.7598 1.498717e-04\n801  1560.9610 1.470159e-04\n802  1562.1622 1.442053e-04\n803  1563.3634 1.414394e-04\n804  1564.5646 1.387177e-04\n805  1565.7658 1.360396e-04\n806  1566.9670 1.334046e-04\n807  1568.1682 1.308123e-04\n808  1569.3694 1.282621e-04\n809  1570.5706 1.257536e-04\n810  1571.7718 1.232863e-04\n811  1572.9730 1.208596e-04\n812  1574.1742 1.184730e-04\n813  1575.3754 1.161262e-04\n814  1576.5766 1.138185e-04\n815  1577.7778 1.115496e-04\n816  1578.9790 1.093188e-04\n817  1580.1802 1.071258e-04\n818  1581.3814 1.049701e-04\n819  1582.5826 1.028511e-04\n820  1583.7838 1.007685e-04\n821  1584.9850 9.872170e-05\n822  1586.1862 9.671027e-05\n823  1587.3874 9.473375e-05\n824  1588.5886 9.279167e-05\n825  1589.7898 9.088358e-05\n826  1590.9910 8.900902e-05\n827  1592.1922 8.716753e-05\n828  1593.3934 8.535867e-05\n829  1594.5946 8.358198e-05\n830  1595.7958 8.183703e-05\n831  1596.9970 8.012336e-05\n832  1598.1982 7.844055e-05\n833  1599.3994 7.678816e-05\n834  1600.6006 7.516576e-05\n835  1601.8018 7.357292e-05\n836  1603.0030 7.200921e-05\n837  1604.2042 7.047422e-05\n838  1605.4054 6.896753e-05\n839  1606.6066 6.748872e-05\n840  1607.8078 6.603738e-05\n841  1609.0090 6.461312e-05\n842  1610.2102 6.321551e-05\n843  1611.4114 6.184417e-05\n844  1612.6126 6.049870e-05\n845  1613.8138 5.917871e-05\n846  1615.0150 5.788380e-05\n847  1616.2162 5.661360e-05\n848  1617.4174 5.536772e-05\n849  1618.6186 5.414578e-05\n850  1619.8198 5.294742e-05\n851  1621.0210 5.177226e-05\n852  1622.2222 5.061994e-05\n853  1623.4234 4.949009e-05\n854  1624.6246 4.838235e-05\n855  1625.8258 4.729638e-05\n856  1627.0270 4.623182e-05\n857  1628.2282 4.518832e-05\n858  1629.4294 4.416554e-05\n859  1630.6306 4.316314e-05\n860  1631.8318 4.218079e-05\n861  1633.0330 4.121815e-05\n862  1634.2342 4.027490e-05\n863  1635.4354 3.935071e-05\n864  1636.6366 3.844527e-05\n865  1637.8378 3.755824e-05\n866  1639.0390 3.668933e-05\n867  1640.2402 3.583823e-05\n868  1641.4414 3.500462e-05\n869  1642.6426 3.418821e-05\n870  1643.8438 3.338871e-05\n871  1645.0450 3.260580e-05\n872  1646.2462 3.183921e-05\n873  1647.4474 3.108866e-05\n874  1648.6486 3.035384e-05\n875  1649.8498 2.963450e-05\n876  1651.0511 2.893035e-05\n877  1652.2523 2.824112e-05\n878  1653.4535 2.756654e-05\n879  1654.6547 2.690635e-05\n880  1655.8559 2.626028e-05\n881  1657.0571 2.562809e-05\n882  1658.2583 2.500951e-05\n883  1659.4595 2.440429e-05\n884  1660.6607 2.381220e-05\n885  1661.8619 2.323298e-05\n886  1663.0631 2.266639e-05\n887  1664.2643 2.211221e-05\n888  1665.4655 2.157019e-05\n889  1666.6667 2.104011e-05\n890  1667.8679 2.052174e-05\n891  1669.0691 2.001485e-05\n892  1670.2703 1.951924e-05\n893  1671.4715 1.903468e-05\n894  1672.6727 1.856095e-05\n895  1673.8739 1.809786e-05\n896  1675.0751 1.764518e-05\n897  1676.2763 1.720273e-05\n898  1677.4775 1.677029e-05\n899  1678.6787 1.634768e-05\n900  1679.8799 1.593470e-05\n901  1681.0811 1.553115e-05\n902  1682.2823 1.513685e-05\n903  1683.4835 1.475162e-05\n904  1684.6847 1.437527e-05\n905  1685.8859 1.400762e-05\n906  1687.0871 1.364850e-05\n907  1688.2883 1.329773e-05\n908  1689.4895 1.295515e-05\n909  1690.6907 1.262058e-05\n910  1691.8919 1.229387e-05\n911  1693.0931 1.197484e-05\n912  1694.2943 1.166335e-05\n913  1695.4955 1.135923e-05\n914  1696.6967 1.106233e-05\n915  1697.8979 1.077250e-05\n916  1699.0991 1.048959e-05\n917  1700.3003 1.021345e-05\n918  1701.5015 9.943950e-06\n919  1702.7027 9.680938e-06\n920  1703.9039 9.424278e-06\n921  1705.1051 9.173833e-06\n922  1706.3063 8.929472e-06\n923  1707.5075 8.691062e-06\n924  1708.7087 8.458475e-06\n925  1709.9099 8.231585e-06\n926  1711.1111 8.010267e-06\n927  1712.3123 7.794400e-06\n928  1713.5135 7.583863e-06\n929  1714.7147 7.378541e-06\n930  1715.9159 7.178317e-06\n931  1717.1171 6.983078e-06\n932  1718.3183 6.792714e-06\n933  1719.5195 6.607115e-06\n934  1720.7207 6.426176e-06\n935  1721.9219 6.249791e-06\n936  1723.1231 6.077857e-06\n937  1724.3243 5.910275e-06\n938  1725.5255 5.746945e-06\n939  1726.7267 5.587769e-06\n940  1727.9279 5.432655e-06\n941  1729.1291 5.281507e-06\n942  1730.3303 5.134236e-06\n943  1731.5315 4.990751e-06\n944  1732.7327 4.850964e-06\n945  1733.9339 4.714791e-06\n946  1735.1351 4.582146e-06\n947  1736.3363 4.452948e-06\n948  1737.5375 4.327115e-06\n949  1738.7387 4.204568e-06\n950  1739.9399 4.085230e-06\n951  1741.1411 3.969025e-06\n952  1742.3423 3.855877e-06\n953  1743.5435 3.745715e-06\n954  1744.7447 3.638468e-06\n955  1745.9459 3.534064e-06\n956  1747.1471 3.432435e-06\n957  1748.3483 3.333516e-06\n958  1749.5495 3.237240e-06\n959  1750.7508 3.143542e-06\n960  1751.9520 3.052361e-06\n961  1753.1532 2.963635e-06\n962  1754.3544 2.877303e-06\n963  1755.5556 2.793307e-06\n964  1756.7568 2.711589e-06\n965  1757.9580 2.632093e-06\n966  1759.1592 2.554764e-06\n967  1760.3604 2.479547e-06\n968  1761.5616 2.406391e-06\n969  1762.7628 2.335243e-06\n970  1763.9640 2.266054e-06\n971  1765.1652 2.198774e-06\n972  1766.3664 2.133354e-06\n973  1767.5676 2.069748e-06\n974  1768.7688 2.007910e-06\n975  1769.9700 1.947794e-06\n976  1771.1712 1.889357e-06\n977  1772.3724 1.832556e-06\n978  1773.5736 1.777348e-06\n979  1774.7748 1.723693e-06\n980  1775.9760 1.671551e-06\n981  1777.1772 1.620882e-06\n982  1778.3784 1.571648e-06\n983  1779.5796 1.523811e-06\n984  1780.7808 1.477337e-06\n985  1781.9820 1.432187e-06\n986  1783.1832 1.388329e-06\n987  1784.3844 1.345727e-06\n988  1785.5856 1.304349e-06\n989  1786.7868 1.264162e-06\n990  1787.9880 1.225135e-06\n991  1789.1892 1.187236e-06\n992  1790.3904 1.150436e-06\n993  1791.5916 1.114705e-06\n994  1792.7928 1.080015e-06\n995  1793.9940 1.046337e-06\n996  1795.1952 1.013644e-06\n997  1796.3964 9.819099e-07\n998  1797.5976 9.511082e-07\n999  1798.7988 9.212136e-07\n1000 1800.0000 8.922015e-07\n```\n\n\n:::\n:::\n\n\n\n## Ejercicio 15 Códigos Gráficos {.small}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gráfico\ngrafico_normal <- ggplot(df_salarios, aes(x = Salario, y = Densidad)) +\n  geom_line(color = \"darkblue\", size = 1) +\n  # Sombreado para X < 1000\n  geom_area(data = filter(df_salarios, Salario < 1000), \n            fill = \"red\", alpha = 0.5) +\n  geom_vline(xintercept = 1200, linetype = \"dashed\", color = \"black\") +\n  labs(title = \"Distribución Normal de Salarios\",\n       subtitle = \"Media = $1200, Desviación Estándar = $150\",\n       x = \"Salario Mensual ($)\",\n       y = \"Densidad de Probabilidad\") +\n  theme_minimal()\n```\n:::\n\n\n\n## Ejercicio 15 Gráfico\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrafico_normal\n```\n\n::: {.cell-output-display}\n![](clase_13_14_practica_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n",
    "supporting": [
      "clase_13_14_practica_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}