---
title: "Contenido "
---

El orden en que serán impartidos los temas puedes ser sujeto a modificaciones.

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Conceptos básicos de la estadística. Definición, estadística descriptiva e inferencial. Introducción a los Datos. Conceptos de Población, Muestra, Variable, clasificación de las variables.                       |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Presentación de datos. Tablas de frecuencia para variables cualitativas y cuantitativas. Gráficos estadísticos.                                                                                                    |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Medidas de tendencia central. Definición. Media aritmética, propiedades y aplicaciones. Media geométrica. Media armónica. Moda. Mediana                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Medidas de ubicación. Definición. Cuartiles, Deciles, Percentiles. Aplicaciones de las medidas de ubicación                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Medidas de dispersión. Concepto. El Rango. Desviación media. Desviación cuartil. La Varianza, propiedades. Desviación típica. El coeficiente de variación, aplicaciones. Momentos. Medidas de asimetría y curtosis |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Números índice. Definiciones, propiedades, tipos y aplicaciones                                                                                                                                                    |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Análisis de correlación y regresión lineal \|                                                                                                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Introducción a la teoría de la probabilidad                                                                                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Introducción al estudio de las variables aleatorias.                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
