{
  "hash": "f2eba8999b44cefd6f171b3df47d5d7b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estadística I\"\nsubtitle: \"clase 15: coeficiente de correlación de Pearson\"\nformat: revealjs\ndate: \"2026/02/09\"\nlang: es\nincremental: true\nauto-stretch: false\nfig-align: center\nexecute:\n  echo: false\n  eval: true\n  fig-align: center\n---\n\n\n\n## Coeficiente de Correlación de Pearson\n\n-   El **coeficiente de correlación de Pearson** ($r$) es una medida estadística que cuantifica la **fuerza** y la **dirección** de la relación lineal entre dos variables cuantitativas.\n-   Es una herramienta fundamental en estadística para entender cómo se mueven dos variables de un mismo cojunto de datos en distintas observaciones.\n-   El valor de $r$ siempre se encuentra entre -1 y +1.\n\n------------------------------------------------------------------------\n\n## Interpretación del Coeficiente $r$\n\n-   $r > 0$: Indica una correlación **positiva**. A medida que una variable aumenta, la otra tiende a aumentar.\n-   $r < 0$: Indica una correlación **negativa**. A medida que una variable aumenta, la otra tiende a disminuir.\n-   $r \\approx 0$: Indica una correlación **débil** o nula entre las variables.\n-   La magnitud de $r$ indica la fuerza de la relación lineal:\n    -   Cercano a $\\pm 1$: Correlación lineal fuerte.\n    -   Cercano a 0: Correlación lineal débil.\n\n------------------------------------------------------------------------\n\n## La Fórmula del Coeficiente de Correlación de Pearson {.small}\n\nEl coeficiente de correlación de Pearson se calcula mediante la siguiente fórmula:\n\n$$r = \\frac{\\sum_{i=1}^{n} (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum_{i=1}^{n} (x_i - \\bar{x})^2} \\sqrt{\\sum_{i=1}^{n} (y_i - \\bar{y})^2}}$$\n\nDonde:\n\n\\- $n$ es el número de pares de datos.\n\n\\- $x_i$ y $y_i$ son los valores individuales de las dos variables.\n\n\\- $\\bar{x}$ es la media de los valores de $x$.\n\n\\- $\\bar{y}$ es la media de los valores de $y$.\n\n------------------------------------------------------------------------\n\n## Ejemplo de Cálculo\n\nConsideremos el siguiente conjunto de datos sobre horas de estudio ($X$) y calificaciones obtenidas ($Y$):\n\n| Estudiante | Horas de Estudio ($X$) | Calificación ($Y$) |\n|:----------:|:----------------------:|:------------------:|\n|     1      |           2            |         5          |\n|     2      |           3            |         7          |\n|     3      |           4            |         8          |\n\n## Gráfico de Dispersión\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](clase_15_02coefR_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n\n## Ejemplo de Cálculo-cont.\n\nVamos a calcular el coeficiente de correlación $r$.\n\nPrimero, calculamos las medias:\n\n<br>\n\n$$\\bar{x} = \\frac{2+3+4}{3} = 3$$\n\n<br>\n\n$$\\bar{y} = \\frac{5+7+8}{3} \\approx 6.67$$\n\nLuego, calculamos los términos necesarios para la fórmula:\n\n## Ejemplo de Cálculo-cont. {style=\".small\"}\n\n| $x_i$ | $y_i$ | $x_i - \\bar{x}$ | $y_i - \\bar{y}$ | $(x_i - \\bar{x})(y_i - \\bar{y})$ | $(x_i - \\bar{x})^2$ | $(y_i - \\bar{y})^2$ |\n|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|\n| 2 | 5 | -1 | -1.67 | 1.67 | 1 | 2.79 |\n| 3 | 7 | 0 | 0.33 | 0 | 0 | 0.11 |\n| 4 | 8 | 1 | 1.33 | 1.33 | 1 | 1.77 |\n|  |  |  |  | $\\sum = 3.00$ | $\\sum = 2$ | $\\sum = 4.67$ |\n\n------------------------------------------------------------------------\n\n## Resultado del Ejemplo\n\nSustituyendo los valores en la fórmula:\n\n$$r = \\frac{3.00}{\\sqrt{2} \\sqrt{4.67}} = \\frac{3.00}{\\sqrt{9.34}} \\approx \\frac{3.00}{3.06} \\approx 0.98$$\n\n-   El valor de $r \\approx 0.98$ indica una **correlación lineal positiva muy fuerte** entre las horas de estudio y las calificaciones obtenidas en este pequeño conjunto de datos. Esto sugiere que a mayor número de horas de estudio, tiende a haber una mayor calificación.\n\n# Descomposición del Coeficiente de Correlación de Pearson (r)\n\n## El Numerador - La Covarianza (Sin normalizar) {.small}\n\nLa parte superior de la fracción es el núcleo de la relación: $$\\sum_{i=1}^{n} (x_i - \\bar{x})(y_i - \\bar{y})$$\n\n-   Mide cómo varían las dos variables conjuntamente.\n-   **Lógica de los signos:**\n    -   Si cuando $x$ sube, $y$ también sube, ambos paréntesis serán positivos (o ambos negativos), dando un resultado **positivo**.\n    -   Si varían en direcciones opuestas, el producto será **negativo**.\n\n## Las Desviaciones Individuales $(x_i - \\bar{x})$ y $(y_i - \\bar{y})$ {.small}\n\nAntes de sumar, la fórmula observa la distancia de cada dato respecto a su propia media.\n\n-   $\\bar{x}$: Es el promedio de la variable $X$.\n-   $\\bar{y}$: Es el promedio de la variable $Y$.\n-   **Propósito:** Al restar la media, estamos \"centrando\" los datos. No nos importa el valor absoluto del dato, sino qué tan lejos está del centro de su propio grupo.\n\n## El Denominador - La Normalización {.small}\n\nLa parte inferior de la fórmula actúa como un \"estandarizador\": $$\\sqrt{\\sum_{i=1}^{n} (x_i - \\bar{x})^2 \\cdot \\sum_{i=1}^{n} (y_i - \\bar{y})^2}$$\n\n-   El numerador depende de las unidades de medida (metros, kilos, etc.). El denominador utiliza las desviaciones cuadráticas para eliminar esas unidades.\n-   **Resultado:** Gracias a esto, el coeficiente $r$ es \"adimensional\" y siempre se mantiene en el rango de -1 a 1, permitiendo comparar peras con manzanas.\n\n## La Variabilidad Total (Suma de Cuadrados)\n\nObservemos los componentes dentro de la raíz:\n\n1\\. $\\sum (x_i - \\bar{x})^2$: Es la suma de los cuadrados de las desviaciones de $X$. Indica cuánta dispersión total hay en la primera variable.\n\n2\\. $\\sum (y_i - \\bar{y})^2$: Lo mismo para la variable $Y$.\n\nAl multiplicar ambas y obtener la raíz cuadrada, estamos calculando una especie de \"variabilidad combinada máxima posible\" que sirve de techo para el numerador.\n\n## Todas las Partes {.small}\n\nEn términos conceptuales, la fórmula se puede entender así:\n\n$$r = \\frac{\\text{Variación Conjunta Real (Covarianza)}}{\\text{Variación Total Posible (Dispersión de X e Y)}}$$\n\n-   Si la **variación conjunta** es igual a la **dispersión total**, el resultado es 1.\n-   Si no hay ninguna relación en el movimiento de las variables, el numerador se vuelve 0, y por tanto, $r = 0$.\n\n## Sensibilidad a Valores Atípicos (Outliers) {.small}\n\nEl coeficiente de Pearson es extremadamente sensible a valores extremos.\n\n-   **El problema de los cuadrados:** Como la fórmula eleva las diferencias al cuadrado $(x_i - \\bar{x})^2$, un solo dato muy alejado del promedio tiene un peso desproporcionado en el resultado final.\n-   **Efecto:** Un solo punto \"atípico\" puede inflar una correlación inexistente o destruir una correlación fuerte, dando una imagen falsa de la realidad de los datos.\n\n## Limitación - Solo Relaciones Lineales {.small}\n\nPearson \"asume\" que la relación entre variables es una línea recta.\n\n-   **Relaciones Curvilíneas:** Si tus datos forman una \"U\" o una curva perfecta, Pearson podría marcar un $r = 0$, sugiriendo que no hay relación cuando en realidad hay una relación estructural muy fuerte (pero no lineal).\n\n    ::: callout-important\n    Siempre es vital visualizar los datos en un diagrama de dispersión antes de confiar ciegamente en el valor de $r$.\n    :::\n",
    "supporting": [
      "clase_15_02coefR_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}